import Foundation
import Testing

/// Pins the deterministic contract `PresetManager.savePreset` enforces
/// on the existing-bundle re-save path. The actual mutation lives on
/// `PresetManifest.applyingSaveRewrites(scaffoldUI:)` and is tested
/// directly here — `PresetManager` itself isn't reachable from the
/// LogicTests target (pulls in `PresetGitCoordinator`, etc.).
///
/// All four rules these tests pin trace back to the 2026-05-08 /try-it
/// sweep:
///
///  - **Failure #2**: re-saving "Sidechain Ducker" with a Rust source
///    after a Python save kept Python's `threshold`/`ratio` defaults
///    in `manifest.params`. Root cause was the bundleExists branch
///    preserving the stale params block; the MCP handler then re-
///    applied it as authoritative metadata, the manifest-priority
///    guard in `readParamNames` skipped the kernel's freshly-extracted
///    metadata, and the wrong values were written straight back to
///    disk. Fix: clear `params` + `_paramsNote` on every re-save.
///
///  - **Failures #1 / #4**: scaffold_ui=true on an existing bundle
///    whose manifest had no `ui` block dropped a starter
///    `ui/index.html` on disk but didn't add the manifest's `ui`
///    block. `BundleUIValidator` then flagged the file as orphaned,
///    and the agent had to hand-author the `ui` block.
///
///  - **Failure #3** (covered by `MCPProtocolCoerceBoolTests`): the
///    schema-correct boolean shape `scaffold_ui: true` was the single
///    happy path; `"true"` (string) silently no-op'd the scaffold.
@Suite("save_preset scaffold-rewrite contract")
struct SavePresetScaffoldRewriteTests {

    // MARK: - Helpers

    /// Build a manifest that mirrors what `PresetBundle.create` would
    /// have written for an earlier "save_preset(scaffold_ui=true,
    /// language=python)" against a Python script that declared a
    /// `PARAMS` dict — the exact precondition for Failure #2.
    private static func pythonManifestWithStaleParams() -> PresetManifest {
        var m = PresetBundle.defaultManifest(language: .python, includeUI: true)
        m.params = [
            PresetManifest.ParamDecl(
                name: "Threshold", key: "threshold",
                min: -60, max: 0, default: -24,
                unit: "dB", curve: "linear", style: "slider", options: nil
            ),
            PresetManifest.ParamDecl(
                name: "Ratio", key: "ratio",
                min: 1, max: 20, default: 4,
                unit: ":1", curve: "linear", style: "slider", options: nil
            ),
        ]
        m.paramsNote = "Auto-generated by ConjureDSP on save. Edit PARAMS / params!() in your script — changes here will be overwritten."
        return m
    }

    // MARK: - Failure #2: stale params cache is cleared

    @Test("Stale params block is dropped on every re-save")
    func clearsStaleParamsBlock() {
        let stale = Self.pythonManifestWithStaleParams()
        let rewritten = stale.applyingSaveRewrites(scaffoldUI: false)
        #expect(rewritten.params == nil,
                "params is a kernel-derived cache — re-saving must clear it so the next compile-and-sync repopulates it from the new source. Failure #2 was the manifest keeping Python's defaults after a Rust re-save.")
        #expect(rewritten.paramsNote == nil,
                "_paramsNote documents the params block; clearing one without the other would leave the warning pointing at nothing.")
    }

    @Test("Stale params block is dropped even when scaffoldUI is also requested")
    func clearsStaleParamsBlockWithScaffoldUI() {
        // The original Run 02 shape: re-save with scaffold_ui=true.
        // Both the params clear AND the ui-block add must happen in
        // one rewrite — they're independent invariants.
        let stale = Self.pythonManifestWithStaleParams()
        let rewritten = stale.applyingSaveRewrites(scaffoldUI: true)
        #expect(rewritten.params == nil)
        #expect(rewritten.paramsNote == nil)
    }

    @Test("Re-save preserves manifest fields outside the cache")
    func preservesUnrelatedFields() {
        var stale = Self.pythonManifestWithStaleParams()
        stale.meta = PresetManifest.Meta(
            author: "test",
            description: "fixture",
            category: "compressor"
        )
        let rewritten = stale.applyingSaveRewrites(scaffoldUI: false)
        #expect(rewritten.meta?.author == "test")
        #expect(rewritten.meta?.description == "fixture")
        #expect(rewritten.meta?.category == "compressor")
        #expect(rewritten.entry == stale.entry)
        #expect(rewritten.language == stale.language)
        #expect(rewritten.schemaVersion == stale.schemaVersion)
    }

    // MARK: - Failures #1 / #4: ui block is added when missing

    @Test("scaffoldUI=true on a manifest without a ui block adds one")
    func addsUIBlockWhenMissing() {
        // Simulates the Run 09 / Run 01 precondition: an existing
        // user bundle whose previous save was scaffold_ui=false (so
        // manifest.ui is nil), now being re-saved with the scaffold
        // flag flipped on.
        let bareManifest = PresetBundle.defaultManifest(language: .python, includeUI: false)
        #expect(bareManifest.ui == nil, "fixture sanity")
        let rewritten = bareManifest.applyingSaveRewrites(scaffoldUI: true)
        #expect(rewritten.ui != nil,
                "scaffold_ui=true must populate manifest.ui — the orphan starter HTML failure (#1, #4) was this branch silently leaving the manifest unchanged.")
        #expect(rewritten.ui?.entryHTML == "ui/index.html")
        // Default opt-in semantics — pure-control UIs are the common
        // case; consumers (cdp-meter / cdp-scope / cdp-bargraph / direct
        // audio.onFrame) must request `audioFrames: true` explicitly.
        // `audio_frames_not_enabled` BundleUIValidator rule catches the
        // mismatch when an author adds a consumer but forgets to flip
        // this flag.
        #expect(rewritten.ui?.audioFrames == false)
    }

    @Test("scaffoldUI=true preserves an existing ui block verbatim")
    func preservesExistingUIBlock() {
        // The agent may have customized fps/dimensions; we must not
        // clobber that just because they re-saved with scaffold_ui=true.
        var manifest = PresetBundle.defaultManifest(language: .python, includeUI: true)
        manifest.ui = PresetManifest.UI(
            entryHTML: "ui/custom.html",
            width: 800,
            height: 600,
            fps: 60,
            audioFrames: false
        )
        let rewritten = manifest.applyingSaveRewrites(scaffoldUI: true)
        #expect(rewritten.ui?.entryHTML == "ui/custom.html")
        #expect(rewritten.ui?.width == 800)
        #expect(rewritten.ui?.height == 600)
        #expect(rewritten.ui?.fps == 60)
        #expect(rewritten.ui?.audioFrames == false)
    }

    @Test("scaffoldUI=false leaves a missing ui block alone")
    func doesNotAddUIBlockWhenScaffoldUIFalse() {
        let bareManifest = PresetBundle.defaultManifest(language: .python, includeUI: false)
        let rewritten = bareManifest.applyingSaveRewrites(scaffoldUI: false)
        #expect(rewritten.ui == nil,
                "scaffoldUI=false re-saves must not silently opt the bundle into a custom UI.")
    }

    // MARK: - scaffoldUIOverrides: per-field merge against defaultScaffoldUI

    /// MCP save_preset's `ui_width`/`ui_height`/`ui_audio_frames` args
    /// route through `scaffoldUIOverrides`. A partial override (just
    /// dimensions) must replace those fields and inherit everything
    /// else from `defaultScaffoldUI` — including `audioFrames: false`,
    /// which is the documented opt-in default.
    @Test("scaffoldUIOverrides replaces named fields and inherits the rest")
    func overridesReplaceNamedFieldsOnly() {
        let bare = PresetBundle.defaultManifest(language: .python, includeUI: false)
        let overrides = PresetManifest.UI(
            entryHTML: nil,
            width: 360, height: 280,
            fps: nil, audioFrames: nil
        )
        let rewritten = bare.applyingSaveRewrites(
            scaffoldUI: true,
            scaffoldUIOverrides: overrides
        )
        #expect(rewritten.ui?.width == 360)
        #expect(rewritten.ui?.height == 280)
        #expect(rewritten.ui?.entryHTML == "ui/index.html",
                "entryHTML not overridden → inherited from defaultScaffoldUI")
        #expect(rewritten.ui?.fps == 30, "fps not overridden → inherited")
        #expect(rewritten.ui?.audioFrames == false,
                "audioFrames not overridden → inherited (documented opt-in default)")
    }

    /// `audioFrames: true` opt-in must roundtrip through the override.
    @Test("scaffoldUIOverrides honors audioFrames=true")
    func overridesHonorAudioFramesTrue() {
        let bare = PresetBundle.defaultManifest(language: .python, includeUI: false)
        let overrides = PresetManifest.UI(
            entryHTML: nil,
            width: 320, height: 360,
            fps: nil, audioFrames: true
        )
        let rewritten = bare.applyingSaveRewrites(
            scaffoldUI: true,
            scaffoldUIOverrides: overrides
        )
        #expect(rewritten.ui?.audioFrames == true)
        #expect(rewritten.ui?.width == 320)
        #expect(rewritten.ui?.height == 360)
    }

    /// `scaffoldUIOverrides` must NOT clobber an existing ui block —
    /// the existing-bundle re-save preserves whatever the author has
    /// already authored. Overrides only apply to the "fresh scaffold
    /// site" case (`copy.ui == nil`).
    @Test("scaffoldUIOverrides ignored when manifest already has a ui block")
    func overridesIgnoredWhenUIBlockExists() {
        var manifest = PresetBundle.defaultManifest(language: .python, includeUI: true)
        manifest.ui = PresetManifest.UI(
            entryHTML: "ui/custom.html",
            width: 800, height: 600,
            fps: 60, audioFrames: true
        )
        let overrides = PresetManifest.UI(
            entryHTML: nil,
            width: 100, height: 100,
            fps: nil, audioFrames: false
        )
        let rewritten = manifest.applyingSaveRewrites(
            scaffoldUI: true,
            scaffoldUIOverrides: overrides
        )
        #expect(rewritten.ui?.width == 800)
        #expect(rewritten.ui?.height == 600)
        #expect(rewritten.ui?.fps == 60)
        #expect(rewritten.ui?.audioFrames == true)
        #expect(rewritten.ui?.entryHTML == "ui/custom.html")
    }

    /// Fresh-bundle path (no existing manifest) also threads overrides
    /// through `defaultManifest(_:includeUI:scaffoldUIOverrides:)`.
    @Test("PresetBundle.defaultManifest applies scaffoldUIOverrides")
    func defaultManifestAppliesOverrides() {
        let overrides = PresetManifest.UI(
            entryHTML: nil,
            width: 480, height: 320,
            fps: nil, audioFrames: true
        )
        let manifest = PresetBundle.defaultManifest(
            language: .rust,
            includeUI: true,
            scaffoldUIOverrides: overrides
        )
        #expect(manifest.ui?.width == 480)
        #expect(manifest.ui?.height == 320)
        #expect(manifest.ui?.audioFrames == true)
        #expect(manifest.ui?.entryHTML == "ui/index.html", "inherited")
        #expect(manifest.ui?.fps == 30, "inherited")
    }

    // MARK: - End-to-end: encode + decode round-trip stays clean

    @Test("Rewritten manifest round-trips through JSON without resurrecting cleared keys")
    func jsonRoundTripDoesNotResurrectClearedKeys() throws {
        let stale = Self.pythonManifestWithStaleParams()
        let rewritten = stale.applyingSaveRewrites(scaffoldUI: true)
        let data = try rewritten.jsonData()
        let json = String(data: data, encoding: .utf8) ?? ""
        // The on-disk manifest must not carry `params` or `_paramsNote`
        // — that's what triggers the manifest-priority guard in
        // `readParamNames` to silently override the kernel-extracted
        // metadata with a Python preset's stale defaults.
        #expect(!json.contains("\"params\""),
                "rewritten manifest still encodes a `params` block: \(json)")
        #expect(!json.contains("_paramsNote"),
                "rewritten manifest still encodes `_paramsNote`: \(json)")
        #expect(json.contains("\"ui\""),
                "rewritten manifest must encode the freshly-added ui block: \(json)")
    }
}
