import Foundation
import Testing

/// Pins that `PresetManifest.applyingSaveRewrites` clears the
/// kernel-derived `telemetry` cache on every re-save. Parallel to
/// `SavePresetScaffoldRewriteTests`, which pins the same contract for
/// `params`/`_paramsNote` and the `ui` block scaffold.
///
/// Same root-cause family as PR #298. `manifest.telemetry` is a cache
/// of slots the script publishes via `ctx.set_telemetry_*` (Rust) or
/// the `TELEMETRY` dict (Python). Re-saving an existing bundle with a
/// new source — especially one that flips language or renames slots —
/// previously left the old telemetry block on disk verbatim, and
/// `BundleUIValidator` then linted `<cdp-meter source="telemetry:…">`
/// references against slot names the new script no longer publishes.
@Suite("save_preset telemetry-rewrite contract")
struct SavePresetTelemetryRewriteTests {

    // MARK: - Helpers

    /// Build a manifest that mirrors what `PresetBundle.create` would
    /// have written for an earlier "save_preset" against a Python
    /// script declaring two telemetry slots — the precondition that
    /// reproduced the stale-telemetry bug deterministically against the
    /// running AU.
    private static func pythonManifestWithStaleTelemetry() -> PresetManifest {
        var m = PresetBundle.defaultManifest(language: .python, includeUI: true)
        m.telemetry = [
            PresetManifest.TelemetryDecl(
                name: "OLD_PHANTOM_SLOT", key: "old_phantom_slot",
                shape: nil, unit: "dB"
            ),
            PresetManifest.TelemetryDecl(
                name: "stale_lower", key: "stale_lower",
                shape: "vector", unit: nil
            ),
        ]
        return m
    }

    // MARK: - Stale telemetry cache is cleared

    @Test("Stale telemetry block is dropped on every re-save")
    func clearsStaleTelemetryBlock() {
        let stale = Self.pythonManifestWithStaleTelemetry()
        let rewritten = stale.applyingSaveRewrites(scaffoldUI: false)
        #expect(rewritten.telemetry == nil,
                "telemetry is a kernel-derived cache — re-saving must clear it so the next compile-and-sync repopulates it from the new source.")
    }

    @Test("Stale telemetry block is dropped even when scaffoldUI is also requested")
    func clearsStaleTelemetryBlockWithScaffoldUI() {
        // Both the telemetry clear AND the ui-block add must happen in
        // one rewrite — they're independent invariants.
        let stale = Self.pythonManifestWithStaleTelemetry()
        let rewritten = stale.applyingSaveRewrites(scaffoldUI: true)
        #expect(rewritten.telemetry == nil)
    }

    @Test("Re-save preserves manifest fields outside the telemetry cache")
    func preservesUnrelatedFields() {
        var stale = Self.pythonManifestWithStaleTelemetry()
        stale.meta = PresetManifest.Meta(
            author: "test",
            description: "fixture",
            category: "telemetry-publisher"
        )
        let rewritten = stale.applyingSaveRewrites(scaffoldUI: false)
        #expect(rewritten.meta?.author == "test")
        #expect(rewritten.meta?.description == "fixture")
        #expect(rewritten.meta?.category == "telemetry-publisher")
        #expect(rewritten.entry == stale.entry)
        #expect(rewritten.language == stale.language)
        #expect(rewritten.schemaVersion == stale.schemaVersion)
    }

    @Test("Re-save also clears params alongside telemetry")
    func clearsBothParamsAndTelemetry() {
        // Both are kernel-derived caches and both must clear in the
        // same rewrite — params (PR #298) and telemetry (this PR) are
        // members of one bug family, fixed by one rewrite primitive.
        var stale = Self.pythonManifestWithStaleTelemetry()
        stale.params = [
            PresetManifest.ParamDecl(
                name: "Threshold", key: "threshold",
                min: -60, max: 0, default: -24,
                unit: "dB", curve: "linear", style: "slider", options: nil
            )
        ]
        stale.paramsNote = "Auto-generated by ConjureDSP on save. Edit PARAMS / params!() in your script — changes here will be overwritten."
        let rewritten = stale.applyingSaveRewrites(scaffoldUI: false)
        #expect(rewritten.params == nil)
        #expect(rewritten.paramsNote == nil)
        #expect(rewritten.telemetry == nil)
    }

    // MARK: - End-to-end: encode + decode round-trip stays clean

    @Test("Rewritten manifest round-trips through JSON without resurrecting the telemetry block")
    func jsonRoundTripDoesNotResurrectTelemetry() throws {
        let stale = Self.pythonManifestWithStaleTelemetry()
        let rewritten = stale.applyingSaveRewrites(scaffoldUI: false)
        let data = try rewritten.jsonData()
        let json = String(data: data, encoding: .utf8) ?? ""
        // The on-disk manifest must not carry a `telemetry` key at all
        // — otherwise BundleUIValidator runs the `<cdp-meter
        // telemetry="…">` lint against the stale slot names.
        #expect(!json.contains("\"telemetry\""),
                "rewritten manifest still encodes a `telemetry` block: \(json)")
    }
}
