use base64::Engine;
use ed25519_dalek::{Signature, Verifier, VerifyingKey};
use serde::Deserialize;

/// Ed25519 public key bytes (32 bytes).
/// Generated by tools/generate-license, embedded here for offline verification.
/// Generated by: cd tools/generate-license && cargo run -- --init
const PUBLIC_KEY_BYTES: [u8; 32] = [
    0x90, 0x7f, 0x2f, 0x36, 0x00, 0x0f, 0x0b, 0x16,
    0x5c, 0xed, 0x38, 0xd9, 0x46, 0x51, 0xee, 0x64,
    0x29, 0x9e, 0x6f, 0x7e, 0xf2, 0xcb, 0xdf, 0x0b,
    0xc0, 0xa5, 0xda, 0x03, 0x14, 0x51, 0xff, 0x7e,
];

#[derive(Debug, Deserialize)]
pub struct LicensePayload {
    pub email: String,
    pub product: String,
    pub created: String,
}

#[derive(Debug)]
pub enum LicenseError {
    /// Missing "." separator or wrong segment count.
    InvalidFormat,
    /// Base64 decoding failed.
    Base64Decode,
    /// Ed25519 signature verification failed.
    InvalidSignature,
    /// JSON parse failed or wrong product field.
    InvalidPayload,
    /// Embedded public key is malformed.
    InvalidPublicKey,
}

impl std::fmt::Display for LicenseError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::InvalidFormat => write!(f, "Invalid serial format"),
            Self::Base64Decode => write!(f, "Failed to decode serial"),
            Self::InvalidSignature => write!(f, "Invalid license signature"),
            Self::InvalidPayload => write!(f, "Invalid license payload"),
            Self::InvalidPublicKey => write!(f, "Invalid public key"),
        }
    }
}

/// Verify a serial key using a specific public key.
///
/// Serial format: `base64(json_payload).base64(ed25519_signature)`
///
/// The signature is verified against the raw JSON bytes (not the base64 encoding).
/// Returns the parsed payload on success, or an error.
pub fn verify_with_key(
    serial: &str,
    public_key_bytes: &[u8; 32],
) -> Result<LicensePayload, LicenseError> {
    let parts: Vec<&str> = serial.trim().splitn(2, '.').collect();
    if parts.len() != 2 {
        return Err(LicenseError::InvalidFormat);
    }

    let engine = base64::engine::general_purpose::STANDARD;

    let payload_bytes = engine
        .decode(parts[0])
        .map_err(|_| LicenseError::Base64Decode)?;
    let sig_bytes = engine
        .decode(parts[1])
        .map_err(|_| LicenseError::Base64Decode)?;

    let signature =
        Signature::from_slice(&sig_bytes).map_err(|_| LicenseError::InvalidSignature)?;
    let verifying_key =
        VerifyingKey::from_bytes(public_key_bytes).map_err(|_| LicenseError::InvalidPublicKey)?;

    verifying_key
        .verify(&payload_bytes, &signature)
        .map_err(|_| LicenseError::InvalidSignature)?;

    let payload: LicensePayload =
        serde_json::from_slice(&payload_bytes).map_err(|_| LicenseError::InvalidPayload)?;

    if payload.product != "conjuredsp" {
        return Err(LicenseError::InvalidPayload);
    }

    Ok(payload)
}

/// Return a pointer to the embedded public key bytes (32 bytes).
/// Used by the UI to display a fingerprint for debugging key mismatches.
pub fn public_key_bytes() -> &'static [u8; 32] {
    &PUBLIC_KEY_BYTES
}

/// Verify a serial key using the embedded production public key.
///
/// Serial format: `base64(json_payload).base64(ed25519_signature)`
///
/// Returns the parsed payload on success, or an error.
pub fn verify_license(serial: &str) -> Result<LicensePayload, LicenseError> {
    verify_with_key(serial, &PUBLIC_KEY_BYTES)
}

#[cfg(test)]
mod tests {
    use super::*;
    use base64::Engine;

    /// Generate a test keypair and return (signing_key, verifying_key_bytes).
    fn test_keypair() -> (ed25519_dalek::SigningKey, [u8; 32]) {
        use ed25519_dalek::SigningKey;
        use rand::rngs::OsRng;
        let signing_key = SigningKey::generate(&mut OsRng);
        let verifying_key_bytes = signing_key.verifying_key().to_bytes();
        (signing_key, verifying_key_bytes)
    }

    /// Sign a payload and return a serial string.
    fn make_serial(signing_key: &ed25519_dalek::SigningKey, payload_json: &str) -> String {
        use ed25519_dalek::Signer;
        let engine = base64::engine::general_purpose::STANDARD;
        let payload_b64 = engine.encode(payload_json.as_bytes());
        let signature = signing_key.sign(payload_json.as_bytes());
        let sig_b64 = engine.encode(signature.to_bytes());
        format!("{}.{}", payload_b64, sig_b64)
    }

    #[test]
    fn test_valid_license_verifies() {
        let (signing_key, pub_bytes) = test_keypair();
        let payload = r#"{"email":"test@example.com","product":"conjuredsp","created":"2026-03-05"}"#;
        let serial = make_serial(&signing_key, payload);

        let result = verify_with_key(&serial, &pub_bytes);
        assert!(result.is_ok());
        let p = result.unwrap();
        assert_eq!(p.email, "test@example.com");
        assert_eq!(p.product, "conjuredsp");
        assert_eq!(p.created, "2026-03-05");
    }

    #[test]
    fn test_tampered_payload_fails() {
        let (signing_key, pub_bytes) = test_keypair();
        let payload = r#"{"email":"test@example.com","product":"conjuredsp","created":"2026-03-05"}"#;
        let serial = make_serial(&signing_key, payload);

        // Tamper: replace payload portion with different email
        let tampered_payload = r#"{"email":"hacker@evil.com","product":"conjuredsp","created":"2026-03-05"}"#;
        let engine = base64::engine::general_purpose::STANDARD;
        let tampered_b64 = engine.encode(tampered_payload.as_bytes());
        let parts: Vec<&str> = serial.splitn(2, '.').collect();
        let tampered_serial = format!("{}.{}", tampered_b64, parts[1]);

        let result = verify_with_key(&tampered_serial, &pub_bytes);
        assert!(matches!(result, Err(LicenseError::InvalidSignature)));
    }

    #[test]
    fn test_wrong_public_key_fails() {
        let (signing_key, _pub_bytes) = test_keypair();
        let (_, wrong_pub_bytes) = test_keypair();
        let payload = r#"{"email":"test@example.com","product":"conjuredsp","created":"2026-03-05"}"#;
        let serial = make_serial(&signing_key, payload);

        let result = verify_with_key(&serial, &wrong_pub_bytes);
        assert!(matches!(result, Err(LicenseError::InvalidSignature)));
    }

    #[test]
    fn test_wrong_product_fails() {
        let (signing_key, pub_bytes) = test_keypair();
        let payload = r#"{"email":"test@example.com","product":"other_plugin","created":"2026-03-05"}"#;
        let serial = make_serial(&signing_key, payload);

        let result = verify_with_key(&serial, &pub_bytes);
        assert!(matches!(result, Err(LicenseError::InvalidPayload)));
    }

    #[test]
    fn test_malformed_serial_no_dot() {
        let (_, pub_bytes) = test_keypair();
        let result = verify_with_key("nodothere", &pub_bytes);
        assert!(matches!(result, Err(LicenseError::InvalidFormat)));
    }

    #[test]
    fn test_invalid_base64() {
        let (_, pub_bytes) = test_keypair();
        let result = verify_with_key("!!!.!!!", &pub_bytes);
        assert!(matches!(result, Err(LicenseError::Base64Decode)));
    }

    #[test]
    fn test_empty_serial() {
        let (_, pub_bytes) = test_keypair();
        let result = verify_with_key("", &pub_bytes);
        assert!(matches!(result, Err(LicenseError::InvalidFormat)));
    }

    #[test]
    fn test_valid_base64_but_invalid_json() {
        let (_, pub_bytes) = test_keypair();
        let engine = base64::engine::general_purpose::STANDARD;
        let payload_b64 = engine.encode(b"not json");
        let fake_sig_b64 = engine.encode(&[0u8; 64]);
        let serial = format!("{}.{}", payload_b64, fake_sig_b64);

        let result = verify_with_key(&serial, &pub_bytes);
        // Will fail at signature verification before JSON parse
        assert!(result.is_err());
    }

    #[test]
    fn test_serial_with_whitespace_trimmed() {
        let (signing_key, pub_bytes) = test_keypair();
        let payload = r#"{"email":"test@example.com","product":"conjuredsp","created":"2026-03-05"}"#;
        let serial = make_serial(&signing_key, payload);

        // Add whitespace/newlines
        let padded = format!("  {} \n", serial);
        let result = verify_with_key(&padded, &pub_bytes);
        assert!(result.is_ok());
    }

    #[test]
    fn test_verify_license_uses_embedded_key() {
        // A random test keypair won't match the embedded production key
        let (signing_key, _) = test_keypair();
        let payload = r#"{"email":"test@example.com","product":"conjuredsp","created":"2026-03-05"}"#;
        let serial = make_serial(&signing_key, payload);

        // verify_license uses the production PUBLIC_KEY_BYTES — a random key's serial should fail
        let result = verify_license(&serial);
        assert!(result.is_err());
    }
}
