/// Safe accessor for audio buffers and parameters in a process() callback.
///
/// Created by the `ctx()` helper function generated by [`setup!`].
/// Wraps raw pointers with channel-sequential indexing.
pub struct Context {
    inp: *const f32,
    out: *mut f32,
    params: *const f32,
    channels: usize,
    frames: usize,
    sample_rate: f32,
}

impl Context {
    /// Create from raw `process()` arguments and PARAMS_BUF pointer.
    ///
    /// # Safety
    /// Caller must guarantee that `input` and `output` are valid for
    /// `channels * frame_count` elements, and `params` is valid for 16 elements.
    #[inline]
    pub unsafe fn new(
        input: *const f32,
        output: *mut f32,
        channels: i32,
        frame_count: i32,
        sample_rate: f32,
        params: *const f32,
    ) -> Self {
        Context {
            inp: input,
            out: output,
            params,
            channels: channels as usize,
            frames: frame_count as usize,
            sample_rate,
        }
    }

    /// Number of audio channels.
    #[inline]
    pub fn channels(&self) -> usize {
        self.channels
    }

    /// Number of frames in this buffer.
    #[inline]
    pub fn frames(&self) -> usize {
        self.frames
    }

    /// Audio sample rate in Hz.
    #[inline]
    pub fn sample_rate(&self) -> f32 {
        self.sample_rate
    }

    /// Read input sample at (channel, frame).
    #[inline]
    pub fn input(&self, channel: usize, frame: usize) -> f32 {
        unsafe { *self.inp.add(channel * self.frames + frame) }
    }

    /// Write output sample at (channel, frame).
    #[inline]
    pub fn set_output(&self, channel: usize, frame: usize, value: f32) {
        unsafe {
            *self.out.add(channel * self.frames + frame) = value;
        }
    }

    /// Read parameter value at the given index.
    #[inline]
    pub fn param(&self, index: usize) -> f32 {
        unsafe { *self.params.add(index) }
    }
}
