/// Number of telemetry slots a script can publish per render block.
/// See [`Context::set_telemetry_scalar`]. Mirrored on the host side as
/// the FFI buffer size for `dsp_kernel_read_telemetry`.
pub const TELEMETRY_LEN: usize = 16;

/// Safe accessor for audio buffers and parameters in a process() callback.
///
/// Created by the `ctx()` helper function generated by [`setup!`].
/// Wraps raw pointers with channel-sequential indexing.
pub struct Context {
    inp: *const f32,
    out: *mut f32,
    params: *const f32,
    telemetry: *mut f32,
    channels: usize,
    frames: usize,
    sample_rate: f32,
}

impl Context {
    /// Create from raw `process()` arguments, the PARAMS_BUF pointer,
    /// and the TELEMETRY_BUF pointer.
    ///
    /// # Safety
    /// Caller must guarantee that `input` and `output` are valid for
    /// `channel_count * frame_count` elements, `params` is valid for 16
    /// elements, and `telemetry` is valid for [`TELEMETRY_LEN`] writes
    /// (or is null, in which case `set_telemetry_scalar` becomes a no-op).
    #[inline]
    pub unsafe fn new(
        input: *const f32,
        output: *mut f32,
        channel_count: i32,
        frame_count: i32,
        sample_rate: f32,
        params: *const f32,
        telemetry: *mut f32,
    ) -> Self {
        Context {
            inp: input,
            out: output,
            params,
            telemetry,
            channels: channel_count as usize,
            frames: frame_count as usize,
            sample_rate,
        }
    }

    /// Number of audio channels.
    #[inline]
    pub fn channels(&self) -> usize {
        self.channels
    }

    /// Number of frames in this buffer.
    #[inline]
    pub fn frames(&self) -> usize {
        self.frames
    }

    /// Audio sample rate in Hz.
    #[inline]
    pub fn sample_rate(&self) -> f32 {
        self.sample_rate
    }

    /// Read input sample at (channel, frame).
    #[inline]
    pub fn input(&self, channel: usize, frame: usize) -> f32 {
        unsafe { *self.inp.add(channel * self.frames + frame) }
    }

    /// Write output sample at (channel, frame).
    #[inline]
    pub fn set_output(&self, channel: usize, frame: usize, value: f32) {
        unsafe {
            *self.out.add(channel * self.frames + frame) = value;
        }
    }

    /// Read parameter value at the given index.
    #[inline]
    pub fn param(&self, index: usize) -> f32 {
        unsafe { *self.params.add(index) }
    }

    /// Publish a single scalar telemetry value for the host UI this block.
    ///
    /// Scalar telemetry is the read-back twin of [`Context::param`]:
    /// write internal DSP state (envelope follower output, computed
    /// gain reduction in dB, sidechain RMS, NAM model magnitude…) and
    /// the host UI receives it via `audio.onFrame`'s `telemetry` field.
    /// Out-of-bounds indices are silently no-op'd. The last write per
    /// index per block wins; the host samples at display-link cadence
    /// (~30–120 Hz), not per-sample.
    ///
    /// For per-frame waveforms (oscilloscope, displacement traces),
    /// declare a `vector_telemetry()` slot in `telemetry!()` and write
    /// it via `set_telemetry_vector` (see vector telemetry plan).
    ///
    /// Pair with the `telemetry!()` macro to declare slot names + units
    /// the UI uses for display formatting.
    #[inline]
    pub fn set_telemetry_scalar(&self, index: usize, value: f32) {
        if index >= TELEMETRY_LEN {
            return;
        }
        if self.telemetry.is_null() {
            return;
        }
        unsafe {
            *self.telemetry.add(index) = value;
        }
    }
}

#[cfg(test)]
mod tests {
    extern crate std;
    use super::*;

    /// Build a Context wrapping caller-provided buffers. All buffers
    /// must outlive the Context.
    unsafe fn ctx_with_telemetry(
        params: &[f32],
        telemetry: &mut [f32],
    ) -> Context {
        // Audio buffers aren't exercised by these tests; pass dangling
        // pointers with zero channels/frames so any accidental access
        // would trip in tests via address sanitization in CI.
        Context::new(
            core::ptr::null(),
            core::ptr::null_mut(),
            0,
            0,
            48000.0,
            params.as_ptr(),
            telemetry.as_mut_ptr(),
        )
    }

    #[test]
    fn set_telemetry_scalar_writes_buf() {
        let params = [0.0_f32; 16];
        let mut buf = [0.0_f32; TELEMETRY_LEN];
        unsafe {
            let ctx = ctx_with_telemetry(&params, &mut buf);
            ctx.set_telemetry_scalar(0, 0.5);
            ctx.set_telemetry_scalar(3, -3.2);
        }
        assert_eq!(buf[0], 0.5);
        assert_eq!(buf[3], -3.2);
        // Untouched slots stay zero.
        assert_eq!(buf[1], 0.0);
        assert_eq!(buf[7], 0.0);
    }

    #[test]
    fn set_telemetry_scalar_last_write_wins() {
        let params = [0.0_f32; 16];
        let mut buf = [0.0_f32; TELEMETRY_LEN];
        unsafe {
            let ctx = ctx_with_telemetry(&params, &mut buf);
            ctx.set_telemetry_scalar(2, 1.0);
            ctx.set_telemetry_scalar(2, 2.0);
            ctx.set_telemetry_scalar(2, -7.5);
        }
        assert_eq!(buf[2], -7.5);
    }

    #[test]
    fn set_telemetry_scalar_out_of_bounds_silent() {
        let params = [0.0_f32; 16];
        let mut buf = [0.0_f32; TELEMETRY_LEN];
        unsafe {
            let ctx = ctx_with_telemetry(&params, &mut buf);
            // No panic, no write past the end.
            ctx.set_telemetry_scalar(TELEMETRY_LEN, 99.0);
            ctx.set_telemetry_scalar(usize::MAX, 99.0);
        }
        assert!(buf.iter().all(|&v| v == 0.0));
    }

    #[test]
    fn set_telemetry_scalar_null_buf_silent() {
        let params = [0.0_f32; 16];
        unsafe {
            let ctx = Context::new(
                core::ptr::null(),
                core::ptr::null_mut(),
                0,
                0,
                48000.0,
                params.as_ptr(),
                core::ptr::null_mut(),
            );
            // No-op when telemetry buffer is null.
            ctx.set_telemetry_scalar(0, 1.0);
            ctx.set_telemetry_scalar(7, 2.0);
        }
    }
}
