/// Number of telemetry slots a script can publish per render block.
/// See [`Context::set_telemetry_scalar`]. Mirrored on the host side as
/// the FFI buffer size for `dsp_kernel_read_telemetry`.
pub const TELEMETRY_LEN: usize = 16;

/// Safe accessor for audio buffers and parameters in a process() callback.
///
/// Created by the `ctx()` helper function generated by [`setup!`].
/// Wraps raw pointers with channel-sequential indexing.
pub struct Context {
    inp: *const f32,
    out: *mut f32,
    params: *const f32,
    telemetry: *mut f32,
    /// Pointer to `SIDECHAIN_BUF` (channel-sequential, MAX_CH * MAX_FR
    /// f32s). Nullable — older `setup!()` versions don't allocate one.
    sidechain: *const f32,
    /// Pointer to `SIDECHAIN_STATE: [i32; 2]` (channel_count, connected
    /// 0/1) written by the host before each `process()` call. Nullable.
    sidechain_state: *const i32,
    /// Per-channel stride for `SIDECHAIN_BUF`. Mirrors the macro's
    /// `MAX_FR` constant and is fixed across blocks (different from
    /// `frames`, which is the live block size).
    sidechain_stride: usize,
    channels: usize,
    frames: usize,
    sample_rate: f32,
}

impl Context {
    /// Create from raw `process()` arguments, the PARAMS_BUF pointer,
    /// and the TELEMETRY_BUF pointer. Sidechain accessors return
    /// silence with `sidechain_connected = false` (use
    /// [`Context::new_with_sidechain`] for sidechain-aware presets).
    ///
    /// # Safety
    /// Caller must guarantee that `input` and `output` are valid for
    /// `channel_count * frame_count` elements, `params` is valid for 16
    /// elements, and `telemetry` is valid for [`TELEMETRY_LEN`] writes
    /// (or is null, in which case `set_telemetry_scalar` becomes a no-op).
    #[inline]
    pub unsafe fn new(
        input: *const f32,
        output: *mut f32,
        channel_count: i32,
        frame_count: i32,
        sample_rate: f32,
        params: *const f32,
        telemetry: *mut f32,
    ) -> Self {
        Context {
            inp: input,
            out: output,
            params,
            telemetry,
            sidechain: core::ptr::null(),
            sidechain_state: core::ptr::null(),
            sidechain_stride: 0,
            channels: channel_count as usize,
            frames: frame_count as usize,
            sample_rate,
        }
    }

    /// Create from raw `process()` arguments plus the sidechain bus
    /// pointers. Used by the `ctx()` helper generated by [`crate::setup`]
    /// — the macro passes `SIDECHAIN_BUF.as_ptr()` and
    /// `SIDECHAIN_STATE.as_ptr()` so accessors don't need to query a
    /// host export per call.
    ///
    /// `sidechain` may be null for presets built against a pre-sidechain
    /// `setup!()` macro (in which case [`Context::sidechain_connected`]
    /// always returns false).
    ///
    /// # Safety
    /// Same as [`Context::new`], plus `sidechain` (when non-null) must
    /// be valid for `2 * crate::MAX_FRAMES` f32 reads, and
    /// `sidechain_state` (when non-null) must be valid for two i32
    /// reads.
    #[inline]
    pub unsafe fn new_with_sidechain(
        input: *const f32,
        output: *mut f32,
        channel_count: i32,
        frame_count: i32,
        sample_rate: f32,
        params: *const f32,
        telemetry: *mut f32,
        sidechain: *const f32,
        sidechain_state: *const i32,
    ) -> Self {
        Context {
            inp: input,
            out: output,
            params,
            telemetry,
            sidechain,
            sidechain_state,
            sidechain_stride: crate::MAX_FRAMES,
            channels: channel_count as usize,
            frames: frame_count as usize,
            sample_rate,
        }
    }

    /// Number of audio channels.
    #[inline]
    pub fn channels(&self) -> usize {
        self.channels
    }

    /// Number of frames in this buffer.
    #[inline]
    pub fn frames(&self) -> usize {
        self.frames
    }

    /// Audio sample rate in Hz.
    #[inline]
    pub fn sample_rate(&self) -> f32 {
        self.sample_rate
    }

    /// Read input sample at (channel, frame).
    #[inline]
    pub fn input(&self, channel: usize, frame: usize) -> f32 {
        unsafe { *self.inp.add(channel * self.frames + frame) }
    }

    /// Write output sample at (channel, frame).
    #[inline]
    pub fn set_output(&self, channel: usize, frame: usize, value: f32) {
        unsafe {
            *self.out.add(channel * self.frames + frame) = value;
        }
    }

    /// Read parameter value at the given index.
    #[inline]
    pub fn param(&self, index: usize) -> f32 {
        unsafe { *self.params.add(index) }
    }

    /// Read sidechain input sample at (channel, frame).
    ///
    /// Returns 0.0 when the host has nothing routed to the sidechain
    /// slot (see [`Context::sidechain_connected`]) or when the script
    /// was built against a pre-sidechain `setup!()` macro. Out-of-range
    /// channel or frame indices clamp to silence rather than reading
    /// past `SIDECHAIN_BUF`.
    #[inline]
    pub fn sidechain(&self, channel: usize, frame: usize) -> f32 {
        if self.sidechain.is_null() {
            return 0.0;
        }
        if channel >= crate::MAX_SIDECHAIN_CHANNELS {
            return 0.0;
        }
        if frame >= self.sidechain_stride {
            return 0.0;
        }
        unsafe { *self.sidechain.add(channel * self.sidechain_stride + frame) }
    }

    /// Number of sidechain channels the host pulled this block. Zero
    /// when nothing is routed; up to 2 in practice.
    #[inline]
    pub fn sidechain_channels(&self) -> usize {
        if self.sidechain_state.is_null() {
            return 0;
        }
        unsafe {
            let n = *self.sidechain_state;
            if n < 0 {
                0
            } else {
                n as usize
            }
        }
    }

    /// Whether the host has audio routed to the sidechain bus this
    /// block. False both when the user hasn't wired a source and when
    /// the script was built against a pre-sidechain `setup!()` macro.
    /// Use this to fall back to internal detection (e.g. compressors
    /// keying off the main input).
    #[inline]
    pub fn sidechain_connected(&self) -> bool {
        if self.sidechain_state.is_null() {
            return false;
        }
        unsafe { *self.sidechain_state.add(1) != 0 }
    }

    /// Publish a single scalar telemetry value for the host UI this block.
    ///
    /// Scalar telemetry is the read-back twin of [`Context::param`]:
    /// write internal DSP state (envelope follower output, computed
    /// gain reduction in dB, sidechain RMS, NAM model magnitude…) and
    /// the host UI receives it via `audio.onFrame`'s `telemetry` field.
    /// Out-of-bounds indices are silently no-op'd. The last write per
    /// index per block wins; the host samples at display-link cadence
    /// (~30–120 Hz), not per-sample.
    ///
    /// For per-frame waveforms (oscilloscope, displacement traces),
    /// declare a `vector_telemetry()` slot in `telemetry!()` and write
    /// it via `set_telemetry_vector` (see vector telemetry plan).
    ///
    /// Pair with the `telemetry!()` macro to declare slot names + units
    /// the UI uses for display formatting.
    #[inline]
    pub fn set_telemetry_scalar(&self, index: usize, value: f32) {
        if index >= TELEMETRY_LEN {
            return;
        }
        if self.telemetry.is_null() {
            return;
        }
        unsafe {
            *self.telemetry.add(index) = value;
        }
    }
}

#[cfg(test)]
mod tests {
    extern crate std;
    use super::*;

    /// Build a Context wrapping caller-provided buffers. All buffers
    /// must outlive the Context.
    unsafe fn ctx_with_telemetry(
        params: &[f32],
        telemetry: &mut [f32],
    ) -> Context {
        // Audio buffers aren't exercised by these tests; pass dangling
        // pointers with zero channels/frames so any accidental access
        // would trip in tests via address sanitization in CI.
        Context::new(
            core::ptr::null(),
            core::ptr::null_mut(),
            0,
            0,
            48000.0,
            params.as_ptr(),
            telemetry.as_mut_ptr(),
        )
    }

    #[test]
    fn set_telemetry_scalar_writes_buf() {
        let params = [0.0_f32; 16];
        let mut buf = [0.0_f32; TELEMETRY_LEN];
        unsafe {
            let ctx = ctx_with_telemetry(&params, &mut buf);
            ctx.set_telemetry_scalar(0, 0.5);
            ctx.set_telemetry_scalar(3, -3.2);
        }
        assert_eq!(buf[0], 0.5);
        assert_eq!(buf[3], -3.2);
        // Untouched slots stay zero.
        assert_eq!(buf[1], 0.0);
        assert_eq!(buf[7], 0.0);
    }

    #[test]
    fn set_telemetry_scalar_last_write_wins() {
        let params = [0.0_f32; 16];
        let mut buf = [0.0_f32; TELEMETRY_LEN];
        unsafe {
            let ctx = ctx_with_telemetry(&params, &mut buf);
            ctx.set_telemetry_scalar(2, 1.0);
            ctx.set_telemetry_scalar(2, 2.0);
            ctx.set_telemetry_scalar(2, -7.5);
        }
        assert_eq!(buf[2], -7.5);
    }

    #[test]
    fn set_telemetry_scalar_out_of_bounds_silent() {
        let params = [0.0_f32; 16];
        let mut buf = [0.0_f32; TELEMETRY_LEN];
        unsafe {
            let ctx = ctx_with_telemetry(&params, &mut buf);
            // No panic, no write past the end.
            ctx.set_telemetry_scalar(TELEMETRY_LEN, 99.0);
            ctx.set_telemetry_scalar(usize::MAX, 99.0);
        }
        assert!(buf.iter().all(|&v| v == 0.0));
    }

    #[test]
    fn sidechain_disconnected_returns_silence_and_false() {
        // `Context::new` (no sidechain pointer) must always report
        // disconnected and return 0.0 for sidechain reads — pins the
        // legacy-context contract used by older `setup!()` macros.
        let params = [0.0_f32; 16];
        let mut tele = [0.0_f32; TELEMETRY_LEN];
        unsafe {
            let ctx = Context::new(
                core::ptr::null(),
                core::ptr::null_mut(),
                0, 0, 48000.0,
                params.as_ptr(),
                tele.as_mut_ptr(),
            );
            assert!(!ctx.sidechain_connected());
            assert_eq!(ctx.sidechain_channels(), 0);
            assert_eq!(ctx.sidechain(0, 0), 0.0);
            assert_eq!(ctx.sidechain(1, 100), 0.0);
        }
    }

    #[test]
    fn sidechain_connected_reads_buf_in_channel_sequential_layout() {
        // Build a fake SIDECHAIN_BUF of MAX_FRAMES per channel and
        // check that `ctx.sidechain(ch, frame)` indexes
        // `ch * MAX_FRAMES + frame` (matches the macro's layout +
        // host's per-channel stride).
        let params = [0.0_f32; 16];
        let mut tele = [0.0_f32; TELEMETRY_LEN];
        let mut sc = vec![0.0_f32; 2 * crate::MAX_FRAMES];
        sc[0] = 0.25;            // ch 0, frame 0
        sc[3] = -0.5;            // ch 0, frame 3
        sc[crate::MAX_FRAMES + 0] = 0.75;  // ch 1, frame 0
        sc[crate::MAX_FRAMES + 7] = -0.125; // ch 1, frame 7
        let state: [i32; 2] = [2, 1];

        unsafe {
            let ctx = Context::new_with_sidechain(
                core::ptr::null(),
                core::ptr::null_mut(),
                0, 16, 48000.0,
                params.as_ptr(),
                tele.as_mut_ptr(),
                sc.as_ptr(),
                state.as_ptr(),
            );
            assert!(ctx.sidechain_connected());
            assert_eq!(ctx.sidechain_channels(), 2);
            assert_eq!(ctx.sidechain(0, 0), 0.25);
            assert_eq!(ctx.sidechain(0, 3), -0.5);
            assert_eq!(ctx.sidechain(1, 0), 0.75);
            assert_eq!(ctx.sidechain(1, 7), -0.125);
        }
    }

    #[test]
    fn sidechain_out_of_range_channel_returns_silence() {
        // Pin the bounds check on the channel index — the buffer is
        // sized for `MAX_SIDECHAIN_CHANNELS` channels (currently 2);
        // anything past that must clamp to silence so a script bug
        // can't read past `SIDECHAIN_BUF`.
        let params = [0.0_f32; 16];
        let mut tele = [0.0_f32; TELEMETRY_LEN];
        let sc = vec![0.5_f32; crate::MAX_SIDECHAIN_CHANNELS * crate::MAX_FRAMES];
        let state: [i32; 2] = [crate::MAX_SIDECHAIN_CHANNELS as i32, 1];

        unsafe {
            let ctx = Context::new_with_sidechain(
                core::ptr::null(),
                core::ptr::null_mut(),
                0, 16, 48000.0,
                params.as_ptr(),
                tele.as_mut_ptr(),
                sc.as_ptr(),
                state.as_ptr(),
            );
            // In-range channels read the buffer.
            assert_eq!(ctx.sidechain(0, 0), 0.5);
            assert_eq!(ctx.sidechain(crate::MAX_SIDECHAIN_CHANNELS - 1, 0), 0.5);
            // Out-of-range channels clamp to silence (no UB read).
            assert_eq!(ctx.sidechain(crate::MAX_SIDECHAIN_CHANNELS, 0), 0.0);
            assert_eq!(ctx.sidechain(crate::MAX_SIDECHAIN_CHANNELS + 5, 0), 0.0);
            assert_eq!(ctx.sidechain(usize::MAX, 0), 0.0);
        }
    }

    #[test]
    fn sidechain_state_reflects_disconnected_flag() {
        // Even when the host wired a buffer, a 0-valued connected flag
        // must surface as `sidechain_connected() == false` so scripts
        // can fall back to internal detection without per-frame logic.
        let params = [0.0_f32; 16];
        let mut tele = [0.0_f32; TELEMETRY_LEN];
        let sc = vec![0.5_f32; 2 * crate::MAX_FRAMES];
        let state: [i32; 2] = [2, 0]; // 2 channels, but flagged disconnected

        unsafe {
            let ctx = Context::new_with_sidechain(
                core::ptr::null(),
                core::ptr::null_mut(),
                0, 16, 48000.0,
                params.as_ptr(),
                tele.as_mut_ptr(),
                sc.as_ptr(),
                state.as_ptr(),
            );
            assert!(!ctx.sidechain_connected());
            // Buffer reads still return whatever's in there — the
            // contract is "if you opt in via `connected`, the buffer
            // is meaningful." Scripts should always branch on
            // `sidechain_connected()` first.
            assert_eq!(ctx.sidechain(0, 0), 0.5);
        }
    }

    #[test]
    fn set_telemetry_scalar_null_buf_silent() {
        let params = [0.0_f32; 16];
        unsafe {
            let ctx = Context::new(
                core::ptr::null(),
                core::ptr::null_mut(),
                0,
                0,
                48000.0,
                params.as_ptr(),
                core::ptr::null_mut(),
            );
            // No-op when telemetry buffer is null.
            ctx.set_telemetry_scalar(0, 1.0);
            ctx.set_telemetry_scalar(7, 2.0);
        }
    }
}
