//
//  LicenseTests.swift
//  ConjureDSPTests
//
//  Integration tests for the Ed25519 license verification pipeline.
//  Tests verify the full stack: serial → Rust FFI verify → kernel state → Swift LicenseManager.
//
//  The test serial is generated at build time by scripts/generate-test-serial.sh
//  and written to .test-serial in the project root. When keypair.bin is not
//  available (e.g. CI or fresh clone), tests skip gracefully.
//

import Testing
import Foundation

struct LicenseTests {

    // MARK: - Test Serial Loading

    /// Read the test serial generated by the build phase.
    /// Returns nil if keypair.bin was missing at build time.
    private static func loadTestSerial() -> String? {
        let projectRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()   // ConjureDSPTests/
            .deletingLastPathComponent()   // project root
        let url = projectRoot.appendingPathComponent(".test-serial")
        guard let serial = try? String(contentsOf: url, encoding: .utf8),
              !serial.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            return nil
        }
        return serial.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    // MARK: - FFI License Verification

    @Test func licenseVerificationViaFFI() throws {
        guard let serial = Self.loadTestSerial() else {
            try #require(Bool(false), "No test serial — keypair.bin not available. Skipping.")
            return
        }

        let kernel = dsp_kernel_create()!
        defer { dsp_kernel_destroy(kernel) }

        // Kernel starts unlicensed
        #expect(!dsp_kernel_is_licensed(kernel))

        // Verify the test serial
        let result = serial.withCString { cStr in
            dsp_kernel_verify_license(kernel, cStr)
        }
        #expect(result, "Test serial should verify successfully against the embedded production key")

        // Kernel is now licensed
        #expect(dsp_kernel_is_licensed(kernel))

        // Demo timer returns infinity when licensed
        let remaining = dsp_kernel_demo_seconds_remaining(kernel, 48000.0)
        #expect(remaining.isInfinite, "Licensed kernel should report infinite demo time remaining")
    }

    @Test func invalidSerialDoesNotLicense() {
        let kernel = dsp_kernel_create()!
        defer { dsp_kernel_destroy(kernel) }

        let result = "invalid.serial".withCString { cStr in
            dsp_kernel_verify_license(kernel, cStr)
        }
        #expect(!result, "Invalid serial should be rejected")
        #expect(!dsp_kernel_is_licensed(kernel), "Kernel should remain unlicensed after invalid serial")

        let errPtr = dsp_kernel_last_error(kernel)
        #expect(errPtr != nil, "Kernel should have an error message after failed verification")
    }

    // MARK: - LicenseManager Integration

    @Test @MainActor func licenseManagerActivation() throws {
        guard let serial = Self.loadTestSerial() else {
            try #require(Bool(false), "No test serial — keypair.bin not available. Skipping.")
            return
        }

        let kernel = dsp_kernel_create()!
        defer { dsp_kernel_destroy(kernel) }

        // Use a temp file for license persistence (test isolation)
        let tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("ConjureDSPLicenseTest-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: tempDir) }
        let tempLicenseFile = tempDir.appendingPathComponent("license.key")

        let lm = LicenseManager(licenseFileURL: tempLicenseFile)
        lm.verifyWithKernel = { s in
            s.withCString { cStr in
                dsp_kernel_verify_license(kernel, cStr)
            }
        }
        lm.getDemoSecondsRemaining = {
            dsp_kernel_demo_seconds_remaining(kernel, 48000.0)
        }

        // Activate with the test serial
        let success = lm.activate(serial: serial)
        #expect(success, "LicenseManager.activate should succeed with test serial")
        #expect(lm.isLicensed, "LicenseManager should report licensed after activation")
        #expect(dsp_kernel_is_licensed(kernel), "Kernel should be licensed after LicenseManager activation")

        // Serial should be persisted to the temp file
        let persisted = try String(contentsOf: tempLicenseFile, encoding: .utf8)
        #expect(persisted == serial, "Serial should be persisted to license file")
    }

    @Test @MainActor func licenseManagerLoadAndVerify() throws {
        guard let serial = Self.loadTestSerial() else {
            try #require(Bool(false), "No test serial — keypair.bin not available. Skipping.")
            return
        }

        let kernel = dsp_kernel_create()!
        defer { dsp_kernel_destroy(kernel) }

        // Pre-write the serial to a temp file (simulating a previously activated license)
        let tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("ConjureDSPLicenseTest-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: tempDir) }
        let tempLicenseFile = tempDir.appendingPathComponent("license.key")
        try serial.write(to: tempLicenseFile, atomically: true, encoding: .utf8)

        let lm = LicenseManager(licenseFileURL: tempLicenseFile)
        lm.verifyWithKernel = { s in
            s.withCString { cStr in
                dsp_kernel_verify_license(kernel, cStr)
            }
        }
        lm.getDemoSecondsRemaining = {
            dsp_kernel_demo_seconds_remaining(kernel, 48000.0)
        }

        // Load and verify the persisted license
        lm.loadAndVerify()
        #expect(lm.isLicensed, "LicenseManager should be licensed after loading persisted serial")
        #expect(dsp_kernel_is_licensed(kernel), "Kernel should be licensed after LicenseManager loadAndVerify")
    }

    // MARK: - Demo Bypass

    @Test func licensedKernelProcessesIndefinitely() throws {
        guard let serial = Self.loadTestSerial() else {
            try #require(Bool(false), "No test serial — keypair.bin not available. Skipping.")
            return
        }

        let kernel = dsp_kernel_create()!
        defer { dsp_kernel_destroy(kernel) }

        // License the kernel
        let verified = serial.withCString { cStr in
            dsp_kernel_verify_license(kernel, cStr)
        }
        #expect(verified)

        // Initialize for mono processing
        dsp_kernel_initialize(kernel, 1, 1, 48000.0)
        dsp_kernel_set_max_frames(kernel, 1024)

        // Process more than DEMO_LIMIT (2,880,000 samples ≈ 60s at 48kHz)
        let framesPerBlock: UInt32 = 1024
        let blocksNeeded = (2_880_000 / Int(framesPerBlock)) + 100 // well past the demo limit

        var inputBuffer = [Float](repeating: 0.5, count: Int(framesPerBlock))
        var outputBuffer = [Float](repeating: 0.0, count: Int(framesPerBlock))

        for _ in 0..<blocksNeeded {
            inputBuffer.withUnsafeBufferPointer { inBuf in
                outputBuffer.withUnsafeMutableBufferPointer { outBuf in
                    var inPtr: UnsafePointer<Float>? = inBuf.baseAddress
                    var outPtr: UnsafeMutablePointer<Float>? = outBuf.baseAddress
                    withUnsafePointer(to: &inPtr) { inPtrPtr in
                        withUnsafeMutablePointer(to: &outPtr) { outPtrPtr in
                            dsp_kernel_process(
                                kernel,
                                inPtrPtr,
                                outPtrPtr,
                                1,     // channels
                                framesPerBlock
                            )
                        }
                    }
                }
            }
        }

        // After processing well past the demo limit, output should NOT be silence
        let hasNonZero = outputBuffer.contains { $0 != 0.0 }
        #expect(hasNonZero, "Licensed kernel should continue processing audio past the demo limit")
    }
}
