#!/bin/bash
# Generate .claude/Worktree.local.xcconfig with per-worktree identifiers so
# Debug builds from different git worktrees don't collide in LaunchServices,
# PluginKit, or when running `open` on the .app.
#
# - In the main worktree: writes an empty override so defaults in
#   Worktree.xcconfig apply (bundle IDs look like com.MichaelJancsy.ConjureDSP.debug,
#   AU subtype DBG1).
# - In a sub-worktree: derives a suffix from the worktree dir name and a
#   1-char AU tag from a SHA-1 hash of that name.
#
# Safe to run on every session start — idempotent; only rewrites when the
# resolved values change.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUTPUT="${REPO_ROOT}/.claude/Worktree.local.xcconfig"

MAIN_WT=$(git -C "${REPO_ROOT}" worktree list --porcelain 2>/dev/null | head -1 | sed 's/worktree //')

ISOLATION_ENABLED="${CD_WORKTREE_ISOLATED:-0}"

if [ "${ISOLATION_ENABLED}" != "1" ] \
   || [ -z "${MAIN_WT}" ] \
   || [ "${REPO_ROOT}" = "${MAIN_WT}" ]; then
    # Default / main repo / opt-out: empty override so Debug builds use
    # the historical bundle IDs (com.MichaelJancsy.ConjureDSP.debug, DBG1)
    # that match the existing App Group provisioning profile.
    #
    # To enable per-worktree IDs (after registering the new bundle IDs in
    # the Apple Developer portal and attaching the App Group capability):
    #     export CD_WORKTREE_ISOLATED=1
    #     ./scripts/setup-worktree-identity.sh
    SUFFIX=""
    AU_TAG="1"
    DISPLAY=""
else
    WORKTREE_NAME="$(basename "${REPO_ROOT}")"

    # Bundle IDs use alphanumerics and hyphens. Strip anything else.
    CLEAN_NAME="$(printf '%s' "${WORKTREE_NAME}" | LC_ALL=C sed 's/[^A-Za-z0-9-]/-/g')"
    SUFFIX=".${CLEAN_NAME}"

    # AU subtype is 4 chars. We use "DBG" + 1 char. Pick a stable
    # hex char from the SHA-1 of the worktree name so different names
    # collide rarely (16 slots, birthday problem hits at ~5 worktrees).
    AU_TAG="$(printf '%s' "${WORKTREE_NAME}" | shasum -a 1 | cut -c1 | tr '[:lower:]' '[:upper:]')"

    DISPLAY=" ${WORKTREE_NAME}"
fi

CONTENT="// AUTO-GENERATED by scripts/setup-worktree-identity.sh — do not edit by hand.
// Regenerates on session start; add worktree name to repro.
CD_WORKTREE_SUFFIX = ${SUFFIX}
CD_WORKTREE_AU_TAG = ${AU_TAG}
CD_WORKTREE_DISPLAY =${DISPLAY}
"

# Only rewrite when content changes — keeps file mtimes stable so Xcode
# doesn't invalidate build caches on every session start.
if [ -f "${OUTPUT}" ] && [ "$(cat "${OUTPUT}")" = "${CONTENT}" ]; then
    echo "✓ Worktree identity current (suffix='${SUFFIX}' au='${AU_TAG}')"
    exit 0
fi

printf '%s' "${CONTENT}" > "${OUTPUT}"
echo "→ Wrote ${OUTPUT} (suffix='${SUFFIX}' au='${AU_TAG}')"
