import numpy as np
import math
from conjuredsp.params import param
from conjuredsp.filters import Biquad, BiquadCoeffs

PARAMS = {
    "speed":     param(0, 1, default=0.5),
    "intensity": param(0, 1, default=0.6),
    "resonance": param(0.5, 8, unit="Q", default=2),
}

_rng_state = 12345

def _rng():
    global _rng_state
    _rng_state = (_rng_state * 1664525 + 1013904223) & 0xFFFFFFFF
    return _rng_state / 4294967296.0

_filters = None
_wind_phase = 0.0
_noise_state = 0.0


def process(inputs, outputs, frame_count, sample_rate, params):
    """
    Wind Filter — wind-like random filtering.

    Applies a bandpass filter that wanders randomly like wind —
    slow, unpredictable sweeps with occasional gusts. The filter
    movement is generated by smoothed random noise, creating
    organic, natural-sounding filter animation. Perfect for ambient
    textures, nature-inspired sound design, and adding life to
    static synth pads.

    Params:
        speed:     Wind change rate (0 = calm, 1 = gusty)
        intensity: Filter sweep range (0 = subtle, 1 = dramatic)
        resonance: Filter sharpness (Q)
    """
    global _filters, _wind_phase, _noise_state

    speed = params["speed"]
    intensity = params["intensity"]
    q = params["resonance"]

    n_ch = len(inputs)

    if _filters is None:
        _filters = [Biquad() for _ in range(n_ch)]

    # Smoothed random walk for organic wind movement
    change_rate = 0.1 + speed * 5.0  # Hz
    smooth = math.exp(-change_rate / sample_rate)

    min_freq = 200.0
    max_freq = 200.0 + intensity * 8000.0
    log_min = math.log(min_freq)
    log_max = math.log(max_freq)

    for i in range(frame_count):
        # Random walk with smoothing
        _noise_state = _noise_state * smooth + (_rng() - 0.5) * (1.0 - smooth) * 2.0
        _noise_state = max(-1.0, min(1.0, _noise_state))

        # Map noise to frequency
        t = (_noise_state + 1.0) * 0.5  # 0 to 1
        sweep_freq = math.exp(log_min + (log_max - log_min) * t)
        sweep_freq = min(sweep_freq, sample_rate * 0.45)

        coeffs = BiquadCoeffs.bandpass(sweep_freq, q, sample_rate)
        for ch in range(n_ch):
            _filters[ch].set_coeffs(coeffs)
            outputs[ch][i] = _filters[ch].process_sample(inputs[ch][i]) * q * 0.3
